config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'posts#index'

  # a custom path for my posts  action
  #get '/my_posts' => 'posts#my_posts', :as => :my_posts

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :comment, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :description, presence: true
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])    
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_post
  before_action :logged_in_user, only: [:create, :destroy]
  
  def index
    @comments = @post.comments
  end

  def new
    @post = Post.find(params[:id])
    @comment = @post.comments.build(comment_params)
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: "Comment created!" }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to post_path(@post), notice: "Comment cannot be empty!" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :comment)
  end

  def get_post
    @post = Post.find(params[:post_id])
  end

  #Only logged in user can post a comment. Check this before entering the create action. 
  def logged_in_user
    unless user_signed_in?
      respond_to do |format|
        format.html { redirect_to post_path(@post), notice: 'You must be logged in to post a comment.' }
        format.json { head :no_content }      
      end
    end    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :check_for_comments, only: [:destroy]

  def index
    if params[:my_posts]&.present? && params[:my_posts] == "true" 
      @posts = current_user.posts.includes(:comments).paginate(page: params[:page], per_page: 2)
    else
      @posts = Post.includes(:comments).paginate(page: params[:page], per_page: 2)
    end
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.limit(7).order('id desc') #to populate the sidebar
    @comment = @post.comments.build
    @comment.user = current_user
    @comments = @post.comments.paginate(page: params[:page], per_page: 3)
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description)
    end

    def check_for_comments
      if @post.comments.any?
        respond_to do |format|
          format.html { redirect_to @post, notice: "You cannot delete post with comments. Delete comments first." }
          format.json { head :no_content }
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <p class="user"><i>	<%= comment.user.first_name + ' ' +  comment.user.last_name %> &bull;</i> <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
  </span><p>
  <p><span class="content"><%= comment.comment %></span>
  </p>
  <% if comment.user == current_user %>
    <p><%= link_to 'Delete comment', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
</li>

app/views/comments/_comment_form.html.erb
<%= form_for [@post, @comment] do |form| %>
  <div class="field mb-3">
    <%= form.label :comment %>
    <%= form.text_area :comment, class: "form-control", placeholder: "Type your comment..." %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">

      <span class="text-muted">&copy; Amir Drljevic</span>
    </div>
  </footer>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
		<%= link_to image_tag("avengers-logo.png", alt: "Avengers logo", width: "100"), root_path%>
    <% link_to 'Avengers App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "New post", new_post_path, class:"nav-link" %>
          </li>            
	        <li class="nav-item">
	          <%= link_to "Edit profile", edit_user_registration_path, class:"nav-link" %>
	        </li>  
					<li class="nav-item">
	          <%= link_to "All posts", posts_path( my_posts: 'false'), class:"nav-link" %>
	        </li> 
	        <li class="nav-item">
	          <%= link_to "Show my posts", posts_path( my_posts: 'true'), class:"nav-link" %>
	        </li>  					
	      <% end %>                        
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0 ">
      	<% if user_signed_in? %>
		      <span class="navbar-text" style="float: right;">
		        	Logged in as: <strong><%= current_user.first_name + ' ' + current_user.last_name %></strong> |
		      </span>   
          <li class="nav-item">
	          <%= link_to "Log out", destroy_user_session_path,
	          						  method: :delete, class:"nav-link" %>
	        </li>   
      	<% else %>
		      <span class="navbar-text" style="float: right;">
		        	<strong>Not logged in</strong> |
		      </span>        	
		      <li class="nav-item">
		        <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
		      </li>   

		      <li class="nav-item">
		        <%= link_to "Log in", new_user_session_path, class:"nav-link" %>
		      </li>   
		     <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <title>Avengers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>    
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>    
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'home/footer' %>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.min.js" integrity="sha384-PsUw7Xwds7x08Ew3exXhqzbhuEYmA2xnwc8BuD6SEr+UmEHlX8/MCltYEodzWA4u" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: "Post title... " %>
  </div>

  <div class="field mb-3">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", placeholder: "Post description...", rows: 10 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>
<br/>
<%= link_to 'Show', @post, class: "btn btn-secondary" %>
<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<%= link_to 'Back', posts_path, class: "btn btn-dark" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @posts %>
  </div>
  <%= will_paginate @posts, :container => true %>
</div>
<div class="row mb-2">
  <% @posts.each do |post| %>
  <div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <h3 class="mb-0"><%= link_to post.title, post, class: "no_style_link" %></h3>
        <div class="mb-1 text-muted"><%= post.created_at.strftime("%_d. %B %Y.") %></div>
        <p class="card-text mb-auto">Author: <%= post.user.first_name + ' ' + post.user.last_name %></p>
        <p><small><i><%= pluralize(post.comments.count, "comment") %></small></i></p>
        <% if post.user == current_user %>
          <div class="d-flex flex-row bd-highlight">
            <div class="p-2 bd-highlight"><%= link_to 'Edit', edit_post_path(post), class: "btn btn-secondary" %> </div>
            <div class="p-2 bd-highlight"><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-secondary" %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>    
  <% end %>    
</div>
<br>
<% if user_signed_in? %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row g-5">
  <div class="col-md-8">
    <article class="blog-post">
      <h2 class="blog-post-title"><%= @post.title %></h2>
      <p class="blog-post-meta"><i><%= @post.created_at.strftime("%_d. %B %Y.") %> <br/><%= @post.user.first_name + ' ' + @post.user.last_name %> </i></p>
      <hr>
      <p><%= @post.description %></p>      
    </article>
    <div class="row">
      <aside class="col-md-8">
        <section class="comment_form">
          <%= render 'comments/comment_form' %>
        </section>
      </aside>
    </div>
    <div class="col-md-8">
      <% if @post.comments.any? %>
      <hr>      
        <h5><%= pluralize(@post.comments.count, "comment") %></h5>
        <ol class="comments">
          <%= render @comments %>
        </ol>
        <div class="digg_pagination">
          <%= will_paginate @comments, :container => true %>
        </div>
      <% end %>
    </div>
    <nav class="blog-pagination" aria-label="Pagination">
    <% if @post.user == current_user %>
      <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-outline-primary" %> 
    <% end %>
      <%= link_to 'Back', posts_path, class: "btn btn-outline-secondary" %>        
    </nav>
  </div>
  <div class="col-md-4">
    <h4>Most recent posts</h4>
    <% @posts.each do |post| %>
      <div class="card sidebar_card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= post.title %></h5>
          <span><i><%= post.created_at.strftime("%_d. %B %Y.") %></i> </span>
          <p class="card-text"><%= truncate(post.description, :length => 70) %></p>
          <%= link_to 'Visit post', post, class: "btn btn-secondary" %>          
        </div>
      </div>
    <% end %>
  </div>
</div>